# Generated by Django 3.2.6 on 2021-11-10 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='full_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
