# Generated by Django 3.2.6 on 2021-11-12 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_order', '0003_auto_20211112_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cast',
            field=models.FloatField(default=0),
        ),
    ]
