# Generated by Django 3.2.8 on 2021-10-25 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_order', '0005_oderdetail_order'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OderDetail',
            new_name='OrderDetail',
        ),
    ]
