# Generated by Django 3.2.6 on 2021-11-27 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_order', '0007_auto_20211127_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='product-image/'),
        ),
    ]
