# Generated by Django 3.2.6 on 2021-11-27 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_order', '0010_customervoucher'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
