# Generated by Django 3.2.6 on 2021-11-09 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_order', '0013_auto_20211106_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='lattitude',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='longitude',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
